modLoader = "javafml" #mandatory
loaderVersion = "[43,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All Rights Reserved"
[[mods]]
    modId = "forcetool"
    version = "${file.jarVersion}"
    displayName = "ForceTool"
    authors = "Bob Varioa"
    description = "Force the correct tool when mining blocks"
[[dependencies.forcetool]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.forcetool]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.2,1.20)"
    ordering = "NONE"
    side = "BOTH"